
cran_packages   <- c("vegan", 
                     "MASS", 
                     "ade4", 
                     "tidyverse", 
                     "FactoMineR", 
                     "cclust",
                     "sNbClust", 
                     "cluster", 
                     "missMDA", 
                     "Hmisc", 
                     "reshape2", 
                     "parallel",
                     "igraph", 
                     "SpiecEasi", 
                     "huge", 
                     "Matrix", 
                     "gtools", 
                     "phyloseq",
                     "microbiome", 
                     "WGCNA", 
                     "brainGraph", 
                     "RCy3", 
                     "RJSONIO","httr",
                     "ggraph", 
                     "devtools", 
                     "ape", 
                     "randomcoloR", 
                     "dendextend",
                     "basicPlotteR"
                     )


bioc_packages   <- c("phyloseq", 
                     "genefilter", 
                     "impute", 
                     "dada2", 
                     "DECIPHER", 
                     "microbiome",
                     "ggtree",
                     "RCy3")
